### ISSUE TITLE
Extend "Complexity Profiling" feature to include APM apps

### ISSUE THREAD

**Issue by iamfuzz** [newrelic/nr1-nimbus#22]
## Summary

Currently, the Complexity Profiling feature only works with fully instrumented web apps:  Browser, APM, and Infra.  For these apps, it is quite useful as the user can create a workload of the app and its underlying hosts with the click of a button, never having to leave the Nimbus UI.

Please extend this functionality to applications only instrumented with APM + Infra.

## Desired Behaviour

The Complexity Profiling page will show a listing of all APM applications that also have infrastructure agents installed on their underlying hosts.

## Possible Solution

Adjust the default algorithm to exclude Browser dependencies or allow for the configuration of the algorithm so that the user can choose to exclude them.

## Additional context

This feature would allow APM users to be able to create workloads without ever having to leave the Nimbus UI.

**Comment by ricegi** [comment]
I've been able to create workloads from the complexity profiler with just APM and Infra dependencies. The feature also includes associated synthetics, mobile, and browser entities when available but isn't a strict dependency. 

Please provide more details, screenshots, or a reference example in an accessible environment.

**Comment by iamfuzz** [comment]
Hi Gil,

I deployed 5 sample apps to the demobot account, and only those instrumented with Browser appear under Complexity Profiling:

![image](https://user-images.githubusercontent.com/221022/95221032-09d77900-07c5-11eb-9639-bb145039341f.png)

![image](https://user-images.githubusercontent.com/221022/95221117-1fe53980-07c5-11eb-98ca-ff3cf57d9433.png)

![image](https://user-images.githubusercontent.com/221022/95221210-35f2fa00-07c5-11eb-9504-730aa42a29a6.png)

Based on your comments, I deployed the latest Nimbus to Demotron_CAS, and indeed, it doesn't appear Browser is the common denominator, but some applications still aren't present ("Box" being one example):

![image](https://user-images.githubusercontent.com/221022/95221777-cd584d00-07c5-11eb-8449-4c10a8e0fc08.png)

![image](https://user-images.githubusercontent.com/221022/95221853-e19c4a00-07c5-11eb-8b1b-0780602be23b.png)

Since Kav based the simple complexity algorithm on this:  https://github.com/iamfuzz/app-complexity-assessement/blob/master/README.md
I dug a little further to see if it was perhaps apps lacking database transactions that were being excluded, but that doesn't appear to be it either.  I'm now not sure why some applications are present and others are not.

**Comment by iamfuzz** [comment]
Digging a bit further, the app GUIDs appear to be retrieved with the following graphql query:

{
  actor {
    account(id: 2246998) {
      nrql(query: "from Relationship select uniques(sourceEntityGuid) where sourceEntityType='APPLICATION'") {
        results
      }
    }
  }
}

For some reason, that query does not return all applications.

**Comment by ricegi** [comment]
might have something to do with those apps not having throughput in the period where the request is being made. It might make more sense to look at how the relationship service is expressed in graphql rather than nrql when creating those dependencies. 

the nrql is a simpler approach would require the recursion multiple entity lookups and subsequent relationship lookups. But will probably be more robust and complete.

**Comment by iamfuzz** [comment]
Good idea, this appears to be the way to do it:

```
{
  actor {
    entitySearch(query: "type IN ('APPLICATION')") {
      results {
        entities {
          guid
        }
        nextCursor
      }
    }
  }
}
```

This has the added benefit of being cross-account as well but will require some pagination work and filtering (this will return two entries for the same app if the app is instrumented with both APM and Browser)

**Comment by ricegi** [comment]
Yes that is a piece of a graph query. 

Switching the mechanism has broader implications  for how the component is built. I am going to close this issue and park this pending a larger design review.
